### ISSUE TITLE
オープンデータポータルのトップページを Pages でホストする

### ISSUE THREAD

**Issue by ShinichiNishikawa** [takamatsu-city/opendata#11]
- ドメイン名は opendata.takamatsu-fact.com 
 - HTML、画像、CSS、SCSSは添付のもの

[opendata_takamatsu_2.zip](https://github.com/takamatsu-city/opendata/files/10956511/opendata_takamatsu_2.zip)

**Comment by ShinichiNishikawa** [comment]
リンク等の設定はまだですが、いったん反映していただけると！

**Comment by champierre** [comment]
https://github.com/takamatsu-city/opendata/commit/b4cc287fe299f860c212b94b2e31f1795a14bf41 で実装しました。
