### ISSUE TITLE
空き行が追加されてしまう

### ISSUE THREAD

**Issue by ShinichiNishikawa** [takamatsu-city/opendata#13]
元のデータに欠損がある場合、空の行ができてしまう

![スクリーンショット 2023-03-15 12 32 07](https://user-images.githubusercontent.com/1124652/225199191-2bd3741c-df00-4af1-be2c-dbc5793d59b0.png)

**期待する動作**

- csv生成時に、空の行は出力されない

**Comment by champierre** [comment]
https://github.com/takamatsu-city/opendata/blob/main/data/hospital/0062.csv <- 変換後は空行が取り除かれます。 @ShinichiNishikawa
