### ISSUE TITLE
環境施設のデータが xlsx 形式でない

### ISSUE THREAD

**Issue by champierre** [takamatsu-city/opendata#14]
https://opendata.smartcity-takamatsu.jp/ckan/dataset/environmental_facilities

の xlsx のファイルをダウンロードしようとすると、 0001_ttl.txt というファイルがダウンロードされる。

@ShinichiNishikawa

**Comment by ShinichiNishikawa** [comment]
@champierre 上記の引用文の通り、excelとtxtが入れ替わって登録されていたということっぽいので、テキストファイルのリンクからexcelをダウンロードして作業していただければと思います。

**Comment by champierre** [comment]
https://github.com/takamatsu-city/opendata/commit/00553fc612d8975a8169a92ae9dfdcf988f3ed19 で修正しました。

**Comment by champierre** [comment]
クローズします。
