### ISSUE TITLE
フォルダ名のtypo

### ISSUE THREAD

**Issue by champierre** [takamatsu-city/opendata#16]
CKANのdataset名をそのまま採用してデータを移行したが、dataset 名にいくつか typo がある。

- bictcle_rental_port -> bicycle_rental_port (https://raw.githubusercontent.com/takamatsu-city/opendata/main/data/bictcle_rental_port/0024.csv)
- hole -> hall (https://raw.githubusercontent.com/takamatsu-city/opendata/main/data/hole/0033.csv)
- amuseum -> museum (https://raw.githubusercontent.com/takamatsu-city/opendata/main/data/amuseum/0044.csv)

**Comment by ShinichiNishikawa** [comment]
報告だけして済ませたいと思っています。

> 3. CKAN データの dataset 名が誤っている
> 
> ご報告ですが、datasetについている名前に、綴りが間違っているものがありました。
> 
> bictcle_rental_port -> bicycle_rental_port (https://raw.githubusercontent.com/takamatsu-city/opendata/main/data/bictcle_rental_port/0024.csv)
> hole -> hall (https://raw.githubusercontent.com/takamatsu-city/opendata/main/data/hole/0033.csv)
> amuseum -> museum (https://raw.githubusercontent.com/takamatsu-city/opendata/main/data/amuseum/0044.csv)
> 
> この機会に直してしまうことも考えましたが、修正してしまうと、すでに CKAN/FIWARE 経由でデータを活用されている方に迷惑がかかるため、このまま採用しています。
> 
> ※ 混乱: 
>  CKAN/FIWARE 経由でデータを活用されている方が、新しいAPIに移行する際、APIのリクエスト先URLの一部だけを差し替えることで対応ができるはずだが、ファイル名を変えてしまうと、そのデータセット名も変更しなければならなくなる。また、データセット名を変更したことを明確に書いて、作業依頼を行う必要が出てしまう。

**Comment by kogumari** [comment]
> このまま修正しない点、承知しました。
確認いただいたので、クローズしてください。
