### ISSUE TITLE
CKAN にないファイル

### ISSUE THREAD

**Issue by champierre** [takamatsu-city/opendata#22]
CKAN に以下のファイルが 存在しませんでした。

- [地域・年齢別人口(2020年9月)](https://opendata.smartcity-takamatsu.jp/ckan/dataset/population202009)
- [地域・年齢別人口(2020年12月)](https://opendata.smartcity-takamatsu.jp/ckan/dataset/population202012)
- [地域・年齢別人口(2021年2月)](https://opendata.smartcity-takamatsu.jp/ckan/dataset/population202102) ページからダウンロードできるのは2021年1月のデータ。

**Comment by ShinichiNishikawa** [comment]
確認中。

> 2. 地域・年齢別人口のデータが欠けている
> 
> - [地域・年齢別人口(2020年9月)](https://opendata.smartcity-takamatsu.jp/ckan/dataset/population202009)
> 
> → excel ではなく、こちらのテキストファイルを採用してよいでしょうか？ https://opendata.smartcity-takamatsu.jp/ckan/dataset/population202009/resource/a9a41af0-621e-4528-af46-5f3cebeda220
> 
> - [地域・年齢別人口(2020年12月)](https://opendata.smartcity-takamatsu.jp/ckan/dataset/population202012)
> 
> → excel ではなく、こちらのテキストファイルを採用してよいでしょうか？ https://opendata.smartcity-takamatsu.jp/ckan/dataset/population202012/resource/5dee46f6-ec89-4277-9ad4-aced507c18e4
> 
> - [地域・年齢別人口(2021年2月)](https://opendata.smartcity-takamatsu.jp/ckan/dataset/population202102) 
> 
> ページからダウンロードできるのは2021年1月のデータでした。正しいエクセルファイルをお送りください。

**Comment by ShinichiNishikawa** [comment]
@champierre 上記の引用文の通り、テキストファイルがtsvなのかな？を初回だけ手で直して採用するといいのかな、と思っています。

**Comment by champierre** [comment]
https://github.com/takamatsu-city/opendata/commit/3c7b13c2c99f352449ba751bb89c0d36b9803105 で修正しました。

**Comment by champierre** [comment]
クローズします。
