### ISSUE TITLE
CKAN に PDF しかないオープンデータはどう扱うのか？

### ISSUE THREAD

**Issue by champierre** [takamatsu-city/opendata#23]
小中学校通学区域情報
https://opendata.smartcity-takamatsu.jp/ckan/dataset/school_area_information

は PDF しかないのだが、どう扱うのか？

**Comment by ShinichiNishikawa** [comment]
確認中。

> 1. 小中学校通学区域情報がPDFになっている
> https://opendata.smartcity-takamatsu.jp/ckan/dataset/school_area_information
> 
> こちらは、CKANにのみ掲載されるという整理でよろしいでしょうか。

**Comment by kogumari** [comment]
@champierre 下記、返答です。GitHubでの表示のみで、スマートマップ掲載はなしです。

>現在もCKANにのみ掲載していますので、CKANのみに掲載いただければ結構です。
Excel、PDFなど、データ形式に関わらず、現在CKANにあるデータ→全てGitHubにデータ移行いただき、
その中で現在ダッシュボードに掲載されている情報は同じようにスマートマップに表示お願いいたします。

**Comment by champierre** [comment]
https://github.com/takamatsu-city/opendata/commit/cf744280180a66b97431b3ee534e36dcf00bf2c1 で、小中学校通学区域情報を追加しました。
