### ISSUE TITLE
医療機関データの差し替え

### ISSUE THREAD

**Issue by kogumari** [takamatsu-city/opendata#24]
[医療機関 (1).csv](https://github.com/takamatsu-city/opendata/files/11014152/1.csv)

位置情報付きのものを頂きましたので、差し替えをお願いいたします。 @champierre

**Comment by champierre** [comment]
https://github.com/takamatsu-city/opendata/commit/40d81722c6eda3809b327eea69afc8a9c288af82 @kogumari 差し替えました。

**Comment by champierre** [comment]
クローズします。
