### ISSUE TITLE
CSVが空行の時はGeoJSONには含めない

### ISSUE THREAD

**Issue by naogify** [takamatsu-city/opendata#3]
@champierre 
以下の行の様に空行の場合は、GeoJSON に含めない方が利用しやすいと思うのですがどうでしょうか？
https://github.com/takamatsu-city/opendata/blob/main/data/hospital/0062.csv?plain=1#L15

**Comment by champierre** [comment]
@naogify https://github.com/takamatsu-city/opendata/pull/4 で修正しました。

**Comment by naogify** [comment]
ありがとうございます！クローズします。
