### ISSUE TITLE
「地図から編集」でデータの量が多い場合、メニューも一緒にスクロールされてしまう

### ISSUE THREAD

**Issue by marcofabrika** [takamatsu-city/opendata#32]
100行以上ある場合は上に戻るのが大変なため、fixedしたほうが使いやすそうです
<img width="1129" alt="スクリーンショット 2023-03-22 17 04 59" src="https://user-images.githubusercontent.com/8433892/226840908-fb156252-12d9-4dbb-aac9-2ec893555fb1.png">

**Comment by champierre** [comment]
@marcofabrika https://github.com/geolonia/opendata-editor の issue
