### ISSUE TITLE
MAPで編集する際、詳細が書かれたボックスのテキストが英語の場合はみ出ることがある

### ISSUE THREAD

**Issue by marcofabrika** [takamatsu-city/opendata#33]
<img width="552" alt="スクリーンショット 2023-03-22 17 01 08" src="https://user-images.githubusercontent.com/8433892/226866221-c77af1f8-3f50-42e8-a65b-11c041338db8.png">
word-break: break-all; などで対応可能だと思います

**Comment by champierre** [comment]
@marcofabrika https://github.com/geolonia/opendata-editor/ の issue に移動したので、こちらはクローズします。 https://github.com/geolonia/opendata-editor/issues/16
