### ISSUE TITLE
利用規約ページ内の「オープンデータAPIの活用について」の段落削除

### ISSUE THREAD

**Issue by kogumari** [takamatsu-city/opendata#37]
「オープンデータAPIの活用について」という説明部分については、削除ください。
https://opendata.takamatsu-fact.com/about/

高松市のHPで、APIの説明欄を設け、申請フォーム等整理して掲載する方向のようですので、ここでの掲載は不要となりました。

**Comment by champierre** [comment]
https://github.com/takamatsu-city/opendata/pull/38 で削除しました。 @kogumari
