### ISSUE TITLE
文字コードの変換

### ISSUE THREAD

**Issue by ShinichiNishikawa** [takamatsu-city/opendata#64]
献立情報2023年4月において文字コードの問題が見つかった。
https://opendata.takamatsu-fact.com/menu_information/data.json

市役所のパソコンのexcelがcsvのUTF形式に変換できず、
csv(カンマ区切り）はそのまま表示されているが、
JSONの方は文字化けされている。

GitHub Actions の中で対応が可能か。

**Comment by champierre** [comment]
https://github.com/takamatsu-city/opendata/commit/ab8e2f1b8db06d63ff010b7f62c9ac471e5d5b48 でアップロードされていた学校給食献立情報4月分のデータの文字コードがShiftJISで文字化けしていたので、暫定対応で、UTF-8に変換しておきました。

ファイルをUTF-8に変換した作業内容(Commit)↓
https://github.com/takamatsu-city/opendata/commit/405657f2a673148132758a350727bc871bc3aaf0

**Comment by champierre** [comment]
GitHub Actions の中で対応するようにしました。
ShiftJIS形式の csv を data フォルダに置いても、自動的に utf-8 に変換するようにしました。

https://github.com/takamatsu-city/opendata/commit/4507c06315cbed02c314593aae74ee24143de32b

**Comment by ShinichiNishikawa** [comment]
解決しました。
