### ISSUE TITLE
今後追加するオープンデータについて項目を作成

### ISSUE THREAD

**Issue by kogumari** [takamatsu-city/opendata#73]
- クリーニング所新規開設一覧(0102) 
- 旅館業新規開設一覧(0103)
- 公衆浴場新規開設一覧 (0104)
- 常設興行場新規開設一覧 (0105)
- 仮説興行場新規開設一覧(0106)

**Comment by naogify** [comment]
Closed by https://github.com/takamatsu-city/opendata/pull/76
