### ISSUE TITLE
データを追加手順を減らす

### ISSUE THREAD

**Issue by naogify** [takamatsu-city/opendata#85]
データを追加手順を減らすために、設定ファイルを自動生成する。

## 課題
現状データを追加しようとすると、`location-data-categories.json`、`standard-data-categories.json`、`pdf-data-categories.json`　のどれかの設定ファイルを修正する必要がある。[（参考）](https://github.com/takamatsu-city/opendata/blob/main/INSTRUCTION.md#3-%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E6%9B%B4%E6%96%B0)

但し、その場合 GitHub 上で操作をしようとすると、GitHub 上ではファイルのアップロードと、他のファイルの編集を一度にすることはできないので、ブランチを2つ作成することになり手順が煩雑になる。

## 解決方法

データを追加するときは、作成したディレクトリに `config.yml` と データエクセルファイルを追加することにする。

```
/new-data 
　・ data.xlsx  // データファイル
　・ config.yml // 設定ファイル
```

config.yml
```
category: "environmental_facilities"
name: "環境施設"
filename: "0001.xlsx"
description: ""
historical: false
dataType: "location" // location か pdfか、standart の値を指定する
```

config.json の `dataType` の値によって、GitHub Action で`location-data-categories.json`、`standard-data-categories.json`、`pdf-data-categories.json`を自動生成する。

**Comment by ShinichiNishikawa** [comment]
データとそのメタデータをセットにするのはどうでしょうね。
